### ISSUE TITLE
🐞 is_fake package issues

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#8375]
1.`crew reinstall` doesn't work. (as reported by @Zopolis4 on slack)
2. upgrades to packages which have been converted to `is_fake` should happen before all other package upgrades, to prevent the removal process of the prior non-`is_fake` package causing the deletion of files installed during the upgrade. (as reported by @uberhacker on slack)
e.g.,
1. `packageA` is installed and has a `packageA.filelist`
2. `packageA` converted to an `is_fake` package depending on `packageA_lib` and `packageA_dev`, but the new `is_fake` `packageA` has an empty filelist.
3. `crew upgrade` is run, which causes:
    - `packageA_lib` and `packageA_dev` get installed, replacing files from `packageA`
    - we now get to the `packageA` upgrade, which causes first a `packageA` removal, i.e., removal of all files in `packageA.filelist`. This removes the files just installed from `packageA_lib` and `packageA_dev`... though the system still thinks those files are installed from `packageA_lib`, and `packageA_dev`, and the filelists for those two packages are left untouched.
   - The new `packageA` is now marked as being installed (with no files in its filelist.)

We need to deal with this... maybe one way would be to not remove filelists of packages being converted to `is_fake`, or just not delete files that exist in other filelists?

**Comment by satmandu** [comment]
The relevant section of `crew is:
```
  # remove it just before the file copy
  if @pkg.in_upgrade
    puts 'Removing since upgrade or reinstall...'
    remove @pkg.name
  end
```

**Comment by satmandu** [comment]
I think this is better resolved in `def remove`. We should just not let remove remove files which exist in other packages! That _should_ solve this problem entirely.

**Comment by uberhacker** [comment]
Would ensuring all the `is_fake` packages are upgraded last solve this issue too?

**Comment by satmandu** [comment]
> Would ensuring all the `is_fake` packages are upgraded last solve this issue too?

That's not the root of the problem...

**Comment by Zopolis4** [comment]
Given that the reinstall issue still persists, should this issue be re-opened or should I open a seperate issue?
